/*
 *  Crate: Wyn
 * Module: Win32 - Log
 */

//! Internal module for textualizing or printing out events, errors, and other platform-specific data.

// ================================================================================================================================ //

// Because the items in this module are for debugging purposes, it is okay for things to go unused.
#![allow(unused)]

#[allow(unused_imports)]
use super::*;

// ================================================================================================================================ //

/// Logs a Win32 WNDPROC Event to the error console.
pub fn event(
    label: &str,
    hwnd: sys::HWND,
    umsg: sys::UINT,
    wparam: sys::WPARAM,
    lparam: sys::LPARAM,
) {
    let name = log::msg(umsg);
    eprintln!("{label}: |H: {hwnd:8X} |W: {wparam:16X} |L: {lparam:16X} | ({umsg:4X}) {name}");
}

// ================================================================================================================================ //

/// Returns the name for a given message, if recognized.
pub fn msg(umsg: sys::UINT) -> &'static str {
    match umsg {
        sys::WM_ACTIVATE => "WM_ACTIVATE",
        sys::WM_ACTIVATEAPP => "WM_ACTIVATEAPP",
        sys::WM_AFXFIRST => "WM_AFXFIRST",
        sys::WM_AFXLAST => "WM_AFXLAST",
        sys::WM_APP => "WM_APP",
        sys::WM_APPCOMMAND => "WM_APPCOMMAND",
        sys::WM_ASKCBFORMATNAME => "WM_ASKCBFORMATNAME",
        sys::WM_CANCELJOURNAL => "WM_CANCELJOURNAL",
        sys::WM_CANCELMODE => "WM_CANCELMODE",
        sys::WM_CAPTURECHANGED => "WM_CAPTURECHANGED",
        sys::WM_CHANGECBCHAIN => "WM_CHANGECBCHAIN",
        sys::WM_CHANGEUISTATE => "WM_CHANGEUISTATE",
        sys::WM_CHAR => "WM_CHAR",
        sys::WM_CHARTOITEM => "WM_CHARTOITEM",
        sys::WM_CHILDACTIVATE => "WM_CHILDACTIVATE",
        sys::WM_CLEAR => "WM_CLEAR",
        sys::WM_CLIPBOARDUPDATE => "WM_CLIPBOARDUPDATE",
        sys::WM_CLOSE => "WM_CLOSE",
        sys::WM_COMMAND => "WM_COMMAND",
        sys::WM_COMMNOTIFY => "WM_COMMNOTIFY",
        sys::WM_COMPACTING => "WM_COMPACTING",
        sys::WM_COMPAREITEM => "WM_COMPAREITEM",
        sys::WM_CONTEXTMENU => "WM_CONTEXTMENU",
        sys::WM_COPY => "WM_COPY",
        sys::WM_COPYDATA => "WM_COPYDATA",
        sys::WM_CREATE => "WM_CREATE",
        sys::WM_CTLCOLORBTN => "WM_CTLCOLORBTN",
        sys::WM_CTLCOLORDLG => "WM_CTLCOLORDLG",
        sys::WM_CTLCOLOREDIT => "WM_CTLCOLOREDIT",
        sys::WM_CTLCOLORLISTBOX => "WM_CTLCOLORLISTBOX",
        sys::WM_CTLCOLORMSGBOX => "WM_CTLCOLORMSGBOX",
        sys::WM_CTLCOLORSCROLLBAR => "WM_CTLCOLORSCROLLBAR",
        sys::WM_CTLCOLORSTATIC => "WM_CTLCOLORSTATIC",
        sys::WM_CUT => "WM_CUT",
        sys::WM_DEADCHAR => "WM_DEADCHAR",
        sys::WM_DELETEITEM => "WM_DELETEITEM",
        sys::WM_DESTROY => "WM_DESTROY",
        sys::WM_DESTROYCLIPBOARD => "WM_DESTROYCLIPBOARD",
        sys::WM_DEVICECHANGE => "WM_DEVICECHANGE",
        sys::WM_DEVMODECHANGE => "WM_DEVMODECHANGE",
        sys::WM_DISPLAYCHANGE => "WM_DISPLAYCHANGE",
        sys::WM_DPICHANGED => "WM_DPICHANGED",
        sys::WM_DPICHANGED_AFTERPARENT => "WM_DPICHANGED_AFTERPARENT",
        sys::WM_DPICHANGED_BEFOREPARENT => "WM_DPICHANGED_BEFOREPARENT",
        sys::WM_DRAWCLIPBOARD => "WM_DRAWCLIPBOARD",
        sys::WM_DRAWITEM => "WM_DRAWITEM",
        sys::WM_DROPFILES => "WM_DROPFILES",
        sys::WM_DWMCOLORIZATIONCOLORCHANGED => "WM_DWMCOLORIZATIONCOLORCHANGED",
        sys::WM_DWMCOMPOSITIONCHANGED => "WM_DWMCOMPOSITIONCHANGED",
        sys::WM_DWMNCRENDERINGCHANGED => "WM_DWMNCRENDERINGCHANGED",
        sys::WM_DWMSENDICONICLIVEPREVIEWBITMAP => "WM_DWMSENDICONICLIVEPREVIEWBITMAP",
        sys::WM_DWMSENDICONICTHUMBNAIL => "WM_DWMSENDICONICTHUMBNAIL",
        sys::WM_DWMWINDOWMAXIMIZEDCHANGE => "WM_DWMWINDOWMAXIMIZEDCHANGE",
        sys::WM_ENABLE => "WM_ENABLE",
        sys::WM_ENDSESSION => "WM_ENDSESSION",
        sys::WM_ENTERIDLE => "WM_ENTERIDLE",
        sys::WM_ENTERMENULOOP => "WM_ENTERMENULOOP",
        sys::WM_ENTERSIZEMOVE => "WM_ENTERSIZEMOVE",
        sys::WM_ERASEBKGND => "WM_ERASEBKGND",
        sys::WM_EXITMENULOOP => "WM_EXITMENULOOP",
        sys::WM_EXITSIZEMOVE => "WM_EXITSIZEMOVE",
        sys::WM_FONTCHANGE => "WM_FONTCHANGE",
        sys::WM_GESTURE => "WM_GESTURE",
        sys::WM_GESTURENOTIFY => "WM_GESTURENOTIFY",
        sys::WM_GETDLGCODE => "WM_GETDLGCODE",
        sys::WM_GETDPISCALEDSIZE => "WM_GETDPISCALEDSIZE",
        sys::WM_GETFONT => "WM_GETFONT",
        sys::WM_GETHOTKEY => "WM_GETHOTKEY",
        sys::WM_GETICON => "WM_GETICON",
        sys::WM_GETMINMAXINFO => "WM_GETMINMAXINFO",
        sys::WM_GETOBJECT => "WM_GETOBJECT",
        sys::WM_GETTEXT => "WM_GETTEXT",
        sys::WM_GETTEXTLENGTH => "WM_GETTEXTLENGTH",
        sys::WM_GETTITLEBARINFOEX => "WM_GETTITLEBARINFOEX",
        sys::WM_HANDHELDFIRST => "WM_HANDHELDFIRST",
        sys::WM_HANDHELDLAST => "WM_HANDHELDLAST",
        sys::WM_HELP => "WM_HELP",
        sys::WM_HOTKEY => "WM_HOTKEY",
        sys::WM_HSCROLL => "WM_HSCROLL",
        sys::WM_HSCROLLCLIPBOARD => "WM_HSCROLLCLIPBOARD",
        sys::WM_ICONERASEBKGND => "WM_ICONERASEBKGND",
        sys::WM_IME_CHAR => "WM_IME_CHAR",
        sys::WM_IME_COMPOSITION => "WM_IME_COMPOSITION",
        sys::WM_IME_COMPOSITIONFULL => "WM_IME_COMPOSITIONFULL",
        sys::WM_IME_CONTROL => "WM_IME_CONTROL",
        sys::WM_IME_ENDCOMPOSITION => "WM_IME_ENDCOMPOSITION",
        sys::WM_IME_KEYDOWN => "WM_IME_KEYDOWN",
        //sys::WM_IME_KEYLAST => "WM_IME_KEYLAST",
        sys::WM_IME_KEYUP => "WM_IME_KEYUP",
        sys::WM_IME_NOTIFY => "WM_IME_NOTIFY",
        sys::WM_IME_REQUEST => "WM_IME_REQUEST",
        sys::WM_IME_SELECT => "WM_IME_SELECT",
        sys::WM_IME_SETCONTEXT => "WM_IME_SETCONTEXT",
        sys::WM_IME_STARTCOMPOSITION => "WM_IME_STARTCOMPOSITION",
        sys::WM_INITDIALOG => "WM_INITDIALOG",
        sys::WM_INITMENU => "WM_INITMENU",
        sys::WM_INITMENUPOPUP => "WM_INITMENUPOPUP",
        sys::WM_INPUT => "WM_INPUT",
        sys::WM_INPUTLANGCHANGE => "WM_INPUTLANGCHANGE",
        sys::WM_INPUTLANGCHANGEREQUEST => "WM_INPUTLANGCHANGEREQUEST",
        sys::WM_INPUT_DEVICE_CHANGE => "WM_INPUT_DEVICE_CHANGE",
        sys::WM_KEYDOWN => "WM_KEYDOWN",
        //sys::WM_KEYFIRST => "WM_KEYFIRST",
        sys::WM_KEYLAST => "WM_KEYLAST",
        sys::WM_KEYUP => "WM_KEYUP",
        sys::WM_KILLFOCUS => "WM_KILLFOCUS",
        sys::WM_LBUTTONDBLCLK => "WM_LBUTTONDBLCLK",
        sys::WM_LBUTTONDOWN => "WM_LBUTTONDOWN",
        sys::WM_LBUTTONUP => "WM_LBUTTONUP",
        sys::WM_MBUTTONDBLCLK => "WM_MBUTTONDBLCLK",
        sys::WM_MBUTTONDOWN => "WM_MBUTTONDOWN",
        sys::WM_MBUTTONUP => "WM_MBUTTONUP",
        sys::WM_MDIACTIVATE => "WM_MDIACTIVATE",
        sys::WM_MDICASCADE => "WM_MDICASCADE",
        sys::WM_MDICREATE => "WM_MDICREATE",
        sys::WM_MDIDESTROY => "WM_MDIDESTROY",
        sys::WM_MDIGETACTIVE => "WM_MDIGETACTIVE",
        sys::WM_MDIICONARRANGE => "WM_MDIICONARRANGE",
        sys::WM_MDIMAXIMIZE => "WM_MDIMAXIMIZE",
        sys::WM_MDINEXT => "WM_MDINEXT",
        sys::WM_MDIREFRESHMENU => "WM_MDIREFRESHMENU",
        sys::WM_MDIRESTORE => "WM_MDIRESTORE",
        sys::WM_MDISETMENU => "WM_MDISETMENU",
        sys::WM_MDITILE => "WM_MDITILE",
        sys::WM_MEASUREITEM => "WM_MEASUREITEM",
        sys::WM_MENUCHAR => "WM_MENUCHAR",
        sys::WM_MENUCOMMAND => "WM_MENUCOMMAND",
        sys::WM_MENUDRAG => "WM_MENUDRAG",
        sys::WM_MENUGETOBJECT => "WM_MENUGETOBJECT",
        sys::WM_MENURBUTTONUP => "WM_MENURBUTTONUP",
        sys::WM_MENUSELECT => "WM_MENUSELECT",
        sys::WM_MOUSEACTIVATE => "WM_MOUSEACTIVATE",
        //sys::WM_MOUSEFIRST => "WM_MOUSEFIRST",
        sys::WM_MOUSEHWHEEL => "WM_MOUSEHWHEEL",
        //sys::WM_MOUSELAST => "WM_MOUSELAST",
        sys::WM_MOUSEMOVE => "WM_MOUSEMOVE",
        sys::WM_MOUSEWHEEL => "WM_MOUSEWHEEL",
        sys::WM_MOVE => "WM_MOVE",
        sys::WM_MOVING => "WM_MOVING",
        sys::WM_NCACTIVATE => "WM_NCACTIVATE",
        sys::WM_NCCALCSIZE => "WM_NCCALCSIZE",
        sys::WM_NCCREATE => "WM_NCCREATE",
        sys::WM_NCDESTROY => "WM_NCDESTROY",
        sys::WM_NCHITTEST => "WM_NCHITTEST",
        sys::WM_NCLBUTTONDBLCLK => "WM_NCLBUTTONDBLCLK",
        sys::WM_NCLBUTTONDOWN => "WM_NCLBUTTONDOWN",
        sys::WM_NCLBUTTONUP => "WM_NCLBUTTONUP",
        sys::WM_NCMBUTTONDBLCLK => "WM_NCMBUTTONDBLCLK",
        sys::WM_NCMBUTTONDOWN => "WM_NCMBUTTONDOWN",
        sys::WM_NCMBUTTONUP => "WM_NCMBUTTONUP",
        sys::WM_NCMOUSEHOVER => "WM_NCMOUSEHOVER",
        sys::WM_NCMOUSELEAVE => "WM_NCMOUSELEAVE",
        sys::WM_NCMOUSEMOVE => "WM_NCMOUSEMOVE",
        sys::WM_NCPAINT => "WM_NCPAINT",
        sys::WM_NCPOINTERDOWN => "WM_NCPOINTERDOWN",
        sys::WM_NCPOINTERUP => "WM_NCPOINTERUP",
        sys::WM_NCPOINTERUPDATE => "WM_NCPOINTERUPDATE",
        sys::WM_NCRBUTTONDBLCLK => "WM_NCRBUTTONDBLCLK",
        sys::WM_NCRBUTTONDOWN => "WM_NCRBUTTONDOWN",
        sys::WM_NCRBUTTONUP => "WM_NCRBUTTONUP",
        sys::WM_NCXBUTTONDBLCLK => "WM_NCXBUTTONDBLCLK",
        sys::WM_NCXBUTTONDOWN => "WM_NCXBUTTONDOWN",
        sys::WM_NCXBUTTONUP => "WM_NCXBUTTONUP",
        sys::WM_NEXTDLGCTL => "WM_NEXTDLGCTL",
        sys::WM_NEXTMENU => "WM_NEXTMENU",
        sys::WM_NOTIFY => "WM_NOTIFY",
        sys::WM_NOTIFYFORMAT => "WM_NOTIFYFORMAT",
        sys::WM_NULL => "WM_NULL",
        sys::WM_PAINT => "WM_PAINT",
        sys::WM_PAINTCLIPBOARD => "WM_PAINTCLIPBOARD",
        sys::WM_PAINTICON => "WM_PAINTICON",
        sys::WM_PALETTECHANGED => "WM_PALETTECHANGED",
        sys::WM_PALETTEISCHANGING => "WM_PALETTEISCHANGING",
        sys::WM_PARENTNOTIFY => "WM_PARENTNOTIFY",
        sys::WM_PASTE => "WM_PASTE",
        sys::WM_PENWINFIRST => "WM_PENWINFIRST",
        sys::WM_PENWINLAST => "WM_PENWINLAST",
        sys::WM_POINTERACTIVATE => "WM_POINTERACTIVATE",
        sys::WM_POINTERCAPTURECHANGED => "WM_POINTERCAPTURECHANGED",
        sys::WM_POINTERDEVICECHANGE => "WM_POINTERDEVICECHANGE",
        sys::WM_POINTERDEVICEINRANGE => "WM_POINTERDEVICEINRANGE",
        sys::WM_POINTERDEVICEOUTOFRANGE => "WM_POINTERDEVICEOUTOFRANGE",
        sys::WM_POINTERDOWN => "WM_POINTERDOWN",
        sys::WM_POINTERENTER => "WM_POINTERENTER",
        sys::WM_POINTERHWHEEL => "WM_POINTERHWHEEL",
        sys::WM_POINTERLEAVE => "WM_POINTERLEAVE",
        sys::WM_POINTERROUTEDAWAY => "WM_POINTERROUTEDAWAY",
        sys::WM_POINTERROUTEDRELEASED => "WM_POINTERROUTEDRELEASED",
        sys::WM_POINTERROUTEDTO => "WM_POINTERROUTEDTO",
        sys::WM_POINTERUP => "WM_POINTERUP",
        sys::WM_POINTERUPDATE => "WM_POINTERUPDATE",
        sys::WM_POINTERWHEEL => "WM_POINTERWHEEL",
        sys::WM_POWER => "WM_POWER",
        sys::WM_POWERBROADCAST => "WM_POWERBROADCAST",
        sys::WM_PRINT => "WM_PRINT",
        sys::WM_PRINTCLIENT => "WM_PRINTCLIENT",
        sys::WM_QUERYDRAGICON => "WM_QUERYDRAGICON",
        sys::WM_QUERYENDSESSION => "WM_QUERYENDSESSION",
        sys::WM_QUERYNEWPALETTE => "WM_QUERYNEWPALETTE",
        sys::WM_QUERYOPEN => "WM_QUERYOPEN",
        sys::WM_QUERYUISTATE => "WM_QUERYUISTATE",
        sys::WM_QUEUESYNC => "WM_QUEUESYNC",
        sys::WM_QUIT => "WM_QUIT",
        sys::WM_RBUTTONDBLCLK => "WM_RBUTTONDBLCLK",
        sys::WM_RBUTTONDOWN => "WM_RBUTTONDOWN",
        sys::WM_RBUTTONUP => "WM_RBUTTONUP",
        sys::WM_RENDERALLFORMATS => "WM_RENDERALLFORMATS",
        sys::WM_RENDERFORMAT => "WM_RENDERFORMAT",
        sys::WM_SETCURSOR => "WM_SETCURSOR",
        sys::WM_SETFOCUS => "WM_SETFOCUS",
        sys::WM_SETFONT => "WM_SETFONT",
        sys::WM_SETHOTKEY => "WM_SETHOTKEY",
        sys::WM_SETICON => "WM_SETICON",
        sys::WM_SETREDRAW => "WM_SETREDRAW",
        sys::WM_SETTEXT => "WM_SETTEXT",
        sys::WM_SETTINGCHANGE => "WM_SETTINGCHANGE",
        sys::WM_SHOWWINDOW => "WM_SHOWWINDOW",
        sys::WM_SIZE => "WM_SIZE",
        sys::WM_SIZECLIPBOARD => "WM_SIZECLIPBOARD",
        sys::WM_SIZING => "WM_SIZING",
        sys::WM_SPOOLERSTATUS => "WM_SPOOLERSTATUS",
        sys::WM_STYLECHANGED => "WM_STYLECHANGED",
        sys::WM_STYLECHANGING => "WM_STYLECHANGING",
        sys::WM_SYNCPAINT => "WM_SYNCPAINT",
        sys::WM_SYSCHAR => "WM_SYSCHAR",
        sys::WM_SYSCOLORCHANGE => "WM_SYSCOLORCHANGE",
        sys::WM_SYSCOMMAND => "WM_SYSCOMMAND",
        sys::WM_SYSDEADCHAR => "WM_SYSDEADCHAR",
        sys::WM_SYSKEYDOWN => "WM_SYSKEYDOWN",
        sys::WM_SYSKEYUP => "WM_SYSKEYUP",
        sys::WM_TABLET_FIRST => "WM_TABLET_FIRST",
        sys::WM_TABLET_LAST => "WM_TABLET_LAST",
        sys::WM_TCARD => "WM_TCARD",
        sys::WM_THEMECHANGED => "WM_THEMECHANGED",
        sys::WM_TIMECHANGE => "WM_TIMECHANGE",
        sys::WM_TIMER => "WM_TIMER",
        sys::WM_TOUCH => "WM_TOUCH",
        sys::WM_TOUCHHITTESTING => "WM_TOUCHHITTESTING",
        sys::WM_UNDO => "WM_UNDO",
        //sys::WM_UNICHAR => "WM_UNICHAR",
        sys::WM_UNINITMENUPOPUP => "WM_UNINITMENUPOPUP",
        sys::WM_UPDATEUISTATE => "WM_UPDATEUISTATE",
        sys::WM_USER => "WM_USER",
        sys::WM_USERCHANGED => "WM_USERCHANGED",
        sys::WM_VKEYTOITEM => "WM_VKEYTOITEM",
        sys::WM_VSCROLL => "WM_VSCROLL",
        sys::WM_VSCROLLCLIPBOARD => "WM_VSCROLLCLIPBOARD",
        sys::WM_WINDOWPOSCHANGED => "WM_WINDOWPOSCHANGED",
        sys::WM_WINDOWPOSCHANGING => "WM_WINDOWPOSCHANGING",
        //sys::WM_WININICHANGE => "WM_WININICHANGE",
        sys::WM_WTSSESSION_CHANGE => "WM_WTSSESSION_CHANGE",
        sys::WM_XBUTTONDBLCLK => "WM_XBUTTONDBLCLK",
        sys::WM_XBUTTONDOWN => "WM_XBUTTONDOWN",
        sys::WM_XBUTTONUP => "WM_XBUTTONUP",
        _ => "<???>",
    }
}

// ================================================================================================================================ //
