[package]
name = "rge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wyn = { path = "../wyn" }
gui-sys = { path = "../gui-sys" }
